Add terrain_map_publisher to spirit_utils
robomechanics/spirit-software pull request #35
Opened 2020-09-29 21:36 UTC by jcnorby

And implement in planning examples.

2020-09-29 21:45 UTC, nikolaif399 requested changes

2020-09-29 21:45 UTC, nikolaif399 commented on spirit_utils/include/spirit_utils/ImageToGridmapDemoCustom.hpp
> +class ImageToGridmapDemo
Class doxy brief required

2020-09-29 21:45 UTC, nikolaif399 commented on spirit_utils/include/spirit_utils/ImageToGridmapDemoCustom.hpp
> +  grid_map::GridMap dataSparseMap_;
Doxygen

2020-09-29 21:45 UTC, nikolaif399 commented on spirit_utils/include/spirit_utils/ImageToGridmapDemoCustom.hpp
> +  double maxHeight_;
Separate into two doxy comments (one per var)

2020-09-29 21:45 UTC, nikolaif399 commented on spirit_utils/include/spirit_utils/ImageToGridmapDemoCustom.hpp
> +  bool mapInitialized_;
Doxy

2020-09-29 21:46 UTC, nikolaif399 commented
Need some doxygen comments on the ImageToGridMap class, otherwise looks good. I see you fixed the build warning about depending on grid_map directly.

2020-09-29 21:50 UTC, jcnorby commented
Oh, whoops, good catch - ImageToGridMap was supposed to be deleted, I merged it into the terrain_map_publisher class. Fixed, and updated the yaml and config files as well.

2020-10-01 17:55 UTC, jcnorby reviewed
Can you take a look at this and approve if good?

2020-10-01 17:58 UTC, nikolaif399 approved these changes

2020-10-01 17:59 UTC, merged